name: Python Tests (Ubuntu)

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests with pytest
        working-directory: ./image
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v
